#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT(KC_NO, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, CW_TOGG, CW_TOGG, CW_TOGG, KC_F9, KC_F10, KC_F11, KC_F12, KC_DEL, KC_PSCR, KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_MINS, KC_EQL, KC_NO, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_LBRC, KC_RBRC, KC_BSLS, KC_PGUP, KC_ESC, KC_A, KC_S, KC_D, KC_F, KC_G, KC_BSPC, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT, KC_ENT, KC_PGDN, KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_ENT, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_HOME, KC_UP, KC_LCTL, KC_LGUI, KC_LALT, KC_LSFT, KC_LCTL, KC_RSFT, KC_SPC, KC_RALT, MO(2), KC_END, KC_LEFT, KC_DOWN, KC_RGHT),
    [1] = LAYOUT(KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F10, KC_NO, TG(1), KC_NO, KC_NO, KC_NO, KC_NO, KC_F2, KC_F3, KC_F4, KC_U, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_3, KC_Q, KC_1, KC_2, KC_R, KC_T, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_ESC, KC_4, KC_S, KC_5, KC_F, KC_G, KC_H, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_6, KC_7, KC_8, KC_C, KC_V, KC_B, KC_P, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_9, KC_NO, KC_NO, KC_LSFT, KC_LCTL, LCS_T(KC_TRNS), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO),
    [2] = LAYOUT(QK_BOOT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, TG(1), KC_TRNS, EE_CLR, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MUTE, KC_VOLD, KC_VOLU, KC_TRNS, RM_TOGG, RM_NEXT, RM_SPDU, RM_VALU, RM_HUEU, RM_SATU, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MPLY, KC_MPRV, KC_MNXT, KC_TRNS, KC_HOME, KC_TRNS, RM_PREV, RM_SPDD, RM_VALD, RM_HUED, RM_SATD, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_END, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_VOLU, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MPRV, KC_VOLD, KC_MNXT)
};




#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C


/* 
 * keymap.c
 */

/* 
 * overrides.c
 */
/* See also: */
/* https://docs.qmk.fm/features/key_overrides */
/* Key Overrides */
/* CTRL + PGUP => HOME */
const key_override_t ctrl_pgup_home =
  ko_make_basic(
    MOD_MASK_CTRL,  // Trigger modifiers: any ctrl
    KC_PGUP,        // Trigger key: page-up
    KC_HOME         // Replacement: home
  );

/* CTRL + PGDOWN => END */
const key_override_t ctrl_pgdown_end =
  ko_make_basic(
    MOD_MASK_CTRL,  // Trigger modifiers: any ctrl
    KC_PGDN,        // Trigger key: page-down
    KC_END          // Replacement: end
  );

/* CTRL + UP => CAPSWORD */
const key_override_t ctrl_up_capsword =
  ko_make_basic(
    MOD_MASK_CTRL,      // Trigger modifiers: any ctrl
    KC_UP,              // Trigger key: page-down
    QK_CAPS_WORD_TOGGLE // Replacement: end
  );

// This globally defines all key overrides to be used
const key_override_t *key_overrides[] = {
	&ctrl_pgup_home,
	&ctrl_pgdown_end,
  &ctrl_up_capsword
};

/* 
 * rgb.c
 */
/* Lighting per layer */
#define _LETTERS  KC_A ... KC_Z
#define _NUMBERS  KC_1 ... KC_0
#define _F_KEYS  KC_F1 ... KC_F12
/* MODIFIER_KEYCODE_RANGE already defined in keycodes.h */

/* Layer indicator only on keys with configured keycodes */
/* https://docs.qmk.fm/features/rgb_matrix#callbacks */
bool rgb_matrix_indicators_advanced_user(uint8_t led_min, uint8_t led_max) {
  uint8_t layer = get_highest_layer(layer_state);
  if (layer > 0) {
    for (uint8_t row = 0; row < MATRIX_ROWS; ++row) {
      for (uint8_t col = 0; col < MATRIX_COLS; ++col) {
        uint8_t index = g_led_config.matrix_co[row][col];
        uint8_t keycode = keymap_key_to_keycode(layer, (keypos_t){col,row});
        if (index >= led_min && index < led_max && index != NO_LED) {
          switch (keycode) {
            case _LETTERS:
              rgb_matrix_set_color( index, RGB_MAGENTA );
              break;
            case _NUMBERS:
              rgb_matrix_set_color( index, RGB_CYAN );
              break;
            case _F_KEYS:
              rgb_matrix_set_color( index, RGB_GREEN );
              break;
            /* case AUDIO_KEYCODE_RANGE: */
            /*   rgb_matrix_set_color( index, RGB_GOLD ); */
            /*   break; */
            /* case RGB_MATRIX_KEYCODE_RANGE: */
            /*   rgb_matrix_set_color( index, RGB_YELLOW ); */
            /*   break; */
            default:
              if ( keycode > KC_TRNS ) {
                rgb_matrix_set_color(index, RGB_RED);
              } else {
                rgb_matrix_set_color(index, RGB_OFF);
              }
          }
        }
      }
    }
  }
  return false;
}
